services:
  odoo:
    container_name: odoo_container
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo:18.0
    depends_on:
      - postgres_db
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_LONGPOLLING_PORT}:8072"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./third_party_addons:/mnt/third-party-addons
      - odoo-data:/var/lib/odoo
    entrypoint: "odoo -c /etc/odoo/odoo.conf -u hr_estevez,auth_estevez,menu_estevez,hr_attendance_controls_adv,hr_recruitment_estevez,hr_attendance_estevez --dev xml"

  postgres_db:
    container_name: postgres_container
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
volumes:
  db-data:
  odoo-data:


