name: Deploy Estevez ERP in Compute Engine

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy in Production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'compute-ssh'
        name: SSH into GCE instance
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: '${{ secrets.GCP_INSTANCE_NAME }}'
          zone: '${{ secrets.GCP_INSTANCE_ZONE }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            echo "Entrando como odoo18 y actualizando el repo..."
            sudo su - odoo18 -c "
              cd /opt/odoo18
              if [ ! -d odoo-erp-docker ]; then
                git clone https://github.com/project-dev-estevez/erp-estevez-docker odoo-erp-docker
              else
                cd odoo-erp-docker && git pull
              fi
              cd /opt/odoo18/odoo-erp-docker
              rsync -av --delete ./custom_addons/ /opt/odoo18/odoo-erp/custom_addons/
            "
            echo "Archivos copiados. Reiniciando el servicio odoo18..."
            sudo systemctl restart odoo18
            echo "Servicio odoo18 reiniciado correctamente."

      - id: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
