name: Deploy Estevez ERP in Compute Engine

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy in Production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'compute-ssh'
        name: SSH into GCE instance
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: '${{ secrets.GCP_INSTANCE_NAME }}'
          zone: '${{ secrets.GCP_INSTANCE_ZONE }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            echo "✅ Conectado a la VM"
            echo "📂 Mostrando contenido del home de odoo18:"
            sudo su - odoo18 -c "ls -la ~"
            
            echo "🚀 Entrando al directorio de Odoo..."
            ODOO_DIR=$(sudo su - odoo18 -c "echo \$ODOO_DIR")
            if [ -z "$ODOO_DIR" ]; then
              echo "⚠️ Variable ODOO_DIR no definida, usando valor por defecto"
              ODOO_DIR="/opt/odoo18"
            fi
            
            echo "🔍 Contenido de $ODOO_DIR:"
            sudo su - odoo18 -c "ls -la $ODOO_DIR"
            
            echo "🔄 Verificando servicios de Odoo:"
            sudo su - odoo18 -c "ps aux | grep odoo"
            
            echo "🏁 Proceso completado"
