name: Deploy Estevez ERP in Compute Engine

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy in Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'Auth GCP'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Print Authenticated Project
        run: gcloud config list


